### ISSUE TITLE
Pull on master generated a lot of conflicts

### ISSUE THREAD

**Issue by tkurc** [SBU-BMI/pathomics_analysis#2]
I did a pull on the master branch, and it listed a lot of conflicts. See below. I didn't edit many of these files. 

warning: no common commits
remote: Counting objects: 182, done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 182 (delta 59), reused 160 (delta 43), pack-reused 0
Receiving objects: 100% (182/182), 715.86 KiB, done.
Resolving deltas: 100% (59/59), done.
From https://github.com/SBU-BMI/pathomics_analysis
 * [new branch]      develop    -> origin/develop
 * [new branch]      feature/nscale-integration -> origin/feature/nscale-integration
 * [new branch]      feature/region-check -> origin/feature/region-check
 * [new branch]      hotfix/size-low-up-declump -> origin/hotfix/size-low-up-declump
 + 93633ea...e384ea7 master     -> origin/master  (forced update)
 * [new branch]      release/1.0 -> origin/release/1.0
 * [new branch]      release/pre_v0.9 -> origin/release/pre_v0.9
From https://github.com/SBU-BMI/pathomics_analysis
 * [new tag]         1.0        -> 1.0
 * [new tag]         1.0.1      -> 1.0.1
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging LICENSE
CONFLICT (add/add): Merge conflict in LICENSE
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging nucleusSegmentation/script/exclude_list.txt
CONFLICT (add/add): Merge conflict in nucleusSegmentation/script/exclude_list.txt
Auto-merging nucleusSegmentation/script/type_dictionary.csv
CONFLICT (add/add): Merge conflict in nucleusSegmentation/script/type_dictionary.csv
Auto-merging nucleusSegmentation/src/CMakeLists.txt
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/CMakeLists.txt
Auto-merging nucleusSegmentation/src/app/CMakeLists.txt
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/CMakeLists.txt
Auto-merging nucleusSegmentation/src/app/mainComputeShapeFeatures.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/mainComputeShapeFeatures.cxx
Auto-merging nucleusSegmentation/src/app/mainComputeTileFeatures.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/mainComputeTileFeatures.cxx
Auto-merging nucleusSegmentation/src/app/mainSegmentFeatures.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/mainSegmentFeatures.cxx
Auto-merging nucleusSegmentation/src/app/mainSegmentSmallImage.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/mainSegmentSmallImage.cxx
Auto-merging nucleusSegmentation/src/app/mainTileAndSegmentWSINucleiOutputFeature.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/app/mainTileAndSegmentWSINucleiOutputFeature.cxx
Auto-merging nucleusSegmentation/src/include/BinaryMaskAnalysisFilter.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/BinaryMaskAnalysisFilter.h
Auto-merging nucleusSegmentation/src/include/HierarchicalMeanshiftClusteringFilter.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/HierarchicalMeanshiftClusteringFilter.h
Auto-merging nucleusSegmentation/src/include/HierarchicalMeanshiftClusteringFilter.hxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/HierarchicalMeanshiftClusteringFilter.hxx
Auto-merging nucleusSegmentation/src/include/InputParameters.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/InputParameters.h
Auto-merging nucleusSegmentation/src/include/Logger.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/Logger.h
Auto-merging nucleusSegmentation/src/include/MeanshiftClusteringFilter.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/MeanshiftClusteringFilter.h
Auto-merging nucleusSegmentation/src/include/MeanshiftClusteringFilter.hxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/MeanshiftClusteringFilter.hxx
Auto-merging nucleusSegmentation/src/include/MultipleObjectFeatureAnalysisFilter.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/MultipleObjectFeatureAnalysisFilter.h
Auto-merging nucleusSegmentation/src/include/Normalization.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/Normalization.h
Auto-merging nucleusSegmentation/src/include/PixelOperations.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/PixelOperations.h
Auto-merging nucleusSegmentation/src/include/SFLS.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SFLS.h
Auto-merging nucleusSegmentation/src/include/SFLSLocalChanVeseSegmentor2D.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SFLSLocalChanVeseSegmentor2D.h
Auto-merging nucleusSegmentation/src/include/SFLSLocalChanVeseSegmentor2D.hxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SFLSLocalChanVeseSegmentor2D.hxx
Auto-merging nucleusSegmentation/src/include/SFLSSegmentor2D.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SFLSSegmentor2D.h
Auto-merging nucleusSegmentation/src/include/SFLSSegmentor2D.hxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SFLSSegmentor2D.hxx
Auto-merging nucleusSegmentation/src/include/SingleObjectFeatureAnalysisFilter.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/SingleObjectFeatureAnalysisFilter.h
Auto-merging nucleusSegmentation/src/include/TypeUtils.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/TypeUtils.h
Auto-merging nucleusSegmentation/src/include/itkTypedefs.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/itkTypedefs.h
Auto-merging nucleusSegmentation/src/include/utilityIO.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/utilityIO.h
Auto-merging nucleusSegmentation/src/include/utilityScalarImage.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/utilityScalarImage.h
Auto-merging nucleusSegmentation/src/include/utilityTileAnalysis.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/utilityTileAnalysis.h
Auto-merging nucleusSegmentation/src/include/utilityWholeSlideProcessing.h
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/include/utilityWholeSlideProcessing.h
Auto-merging nucleusSegmentation/src/internal/mainObjectFeaturesToSubjectFeatures.py
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/internal/mainObjectFeaturesToSubjectFeatures.py
Auto-merging nucleusSegmentation/src/lib/BinaryMaskAnalysisFilter.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/BinaryMaskAnalysisFilter.cxx
Auto-merging nucleusSegmentation/src/lib/InputParameters.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/InputParameters.cxx
Auto-merging nucleusSegmentation/src/lib/Logger.cpp
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/Logger.cpp
Auto-merging nucleusSegmentation/src/lib/MultipleObjectFeatureAnalysisFilter.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/MultipleObjectFeatureAnalysisFilter.cxx
Auto-merging nucleusSegmentation/src/lib/Normalization.cpp
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/Normalization.cpp
Auto-merging nucleusSegmentation/src/lib/PixelOperations.cpp
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/PixelOperations.cpp
Auto-merging nucleusSegmentation/src/lib/SingleObjectFeatureAnalysisFilter.cxx
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/SingleObjectFeatureAnalysisFilter.cxx
Auto-merging nucleusSegmentation/src/lib/computeSubjectFeatureFromObjects.py
CONFLICT (add/add): Merge conflict in nucleusSegmentation/src/lib/computeSubjectFeatureFromObjects.py
Auto-merging nucleusSegmentation/test_segmentation/Dockerfile
CONFLICT (add/add): Merge conflict in nucleusSegmentation/test_segmentation/Dockerfile
Auto-merging nucleusSegmentation/test_segmentation/TCGA-CS-4938-01Z-00-DX1_12560_47520_500_500_LGG.png
CONFLICT (add/add): Merge conflict in nucleusSegmentation/test_segmentation/TCGA-CS-4938-01Z-00-DX1_12560_47520_500_500_LGG.png
Automatic merge failed; fix conflicts and then commit the result.

**Comment by tdiprima** [comment]
OK.  Actually, nobody should be committing directly to the master branch.  You should be on the develop branch.  Work your changes, and then merge with master.  This way we keep everything in sync.  Or create a "feature/[your-feature]" branch from develop, and then merge it to the develop and master branch.
The solution for the pull is: please zip/tar/or-otherwise-archive your local pathomics_analysis directory.  Then clone this repository.  And checkout the develop branch.  Prior emails make mention of [gitflow](https://github.com/nvie/gitflow).  If you install it ( `brew install git-flow` ) then go into the pathomics_analysis directory, and do `git flow init`, accept the defaults, and you're ready to go.
